/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by Documentation/scheduler/sched-pelt; do not modify. */

/*
 * 这个文件是 PELT（Per-Entity Load Tracking）的定点常量表，而不是独立的调度逻辑。
 * Documentation/scheduler/sched-pelt.c 在构建这些常量时取 HALFLIFE=32，令
 * y = 2^(-1/32)，于是每经过 32 个约 1ms 的 PELT 小周期，历史贡献约衰减一半。
 * kernel/sched/pelt.c 的 decay_load() 先把完整的 32 周期折算为右移，再用本表处理
 * 余数；这样更新负载时不必逐周期循环，表中的数值也避免了运行时浮点运算。
 *
 * 生成器会在内核源码更新时重新输出本文件，因此这里的学习注释可能被重新生成覆盖。
 * 除了 SPDX 和生成器声明外，下面的数组与宏必须保持为生成器的精确输出；不要把它们
 * 当作可手工调参的调度策略。该文件没有函数、结构体或运行时 ownership，只有被
 * pelt.c 借用的只读常量；数组未被某个配置引用时由 __maybe_unused 避免编译器告警。
 */
#include <linux/types.h>

/*
 * runnable_avg_yN_inv[i] 表示 y^i 的 Q0.32 近似值，即把真实乘法结果放大到
 * 2^32 后取整数。i 的有效范围是 0..LOAD_AVG_PERIOD-1：i=0 的 0xffffffff
 * 近似 1，后续元素随历史年龄增加而递减。pelt.c 用
 * mul_u64_u32_shr(val, runnable_avg_yN_inv[i], 32) 将输入贡献按余数衰减；
 * 完整半衰期由右移承担，所以调用者不能把 i 当作任意长度的周期数，也不能把
 * 这些整数直接当成百分比。该数组是静态只读输入，没有引用计数、锁或生命周期转移。
 */
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
	0xffffffff, 0xfa83b2da, 0xf5257d14, 0xefe4b99a, 0xeac0c6e6, 0xe5b906e6,
	0xe0ccdeeb, 0xdbfbb796, 0xd744fcc9, 0xd2a81d91, 0xce248c14, 0xc9b9bd85,
	0xc5672a10, 0xc12c4cc9, 0xbd08a39e, 0xb8fbaf46, 0xb504f333, 0xb123f581,
	0xad583ee9, 0xa9a15ab4, 0xa5fed6a9, 0xa2704302, 0x9ef5325f, 0x9b8d39b9,
	0x9837f050, 0x94f4efa8, 0x91c3d373, 0x8ea4398a, 0x8b95c1e3, 0x88980e80,
	0x85aac367, 0x82cd8698,
};

/*
 * 一个 PELT 半衰期包含 32 个小周期。pelt.c 用它把 n 拆成
 * n / LOAD_AVG_PERIOD 个右移和 n % LOAD_AVG_PERIOD 个查表索引；该拆分是
 * 指数衰减近似能够保持常数时间的关键。小周期的实际时间基准由调用者的 PELT
 * 时间轴决定，这个宏本身是周期计数，不是纳秒或调度 tick。
 */
#define LOAD_AVG_PERIOD 32

/*
 * LOAD_AVG_MAX 是连续活动信号趋近的定点上限，由生成器反复计算
 * max = max * y + 1024 直到收敛得到 47742。pelt.c 用它计算完整周期的等比和，
 * 并把 runnable_sum 等聚合量限制在相同刻度；1024 是 PELT 每个小周期的基础贡献。
 * 它不是 CPU 容量，也不是任务权重：改变该值会破坏衰减表、求和公式和边界判断之间
 * 的共同刻度，因此只能随生成器输出一起更新。
 */
#define LOAD_AVG_MAX 47742
